name: CampFire
description: Lets build a CampFire for awesome Looks on your server.
version: 1.0
main: nl.Wesley.Main.CampFire
authors: [78wesley]
commands:
    campfire:
        description: CampFire command.
        permission: campfire.command.use

permissions:
    campfire.command.use:
        description: Gives access to all campfire commands.
    campfire.command.add:
        description: Gives access to add campfire command.
    campfire.command.remove:
        description: Gives access to remove campfire command.
    campfire.command.debug:
        description: Gives access to debug campfire command.
    campfire.command.list:
        description: Gives access to list campfire command.
    campfire.command.on:
        description: Gives access to on campfire command.
    campfire.command.off:
        description: Gives access to off campfire command.